image:
  file: .gitpod.Dockerfile
tasks:
  - name: tailscaled
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TS_STATE_TAILSCALE_EXAMPLE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod@nooobcoder-${GITPOD_WORKSPACE_ID}" \
                          --authkey "${TAILSCALE_AUTHKEY}"
  - name: Import GPG
    init: >
      [[ ! -z $GNUPG_KEY  ]] &&
      gpg --verbose --batch --import <(echo $GNUPG_KEY|base64 -d) &&
      echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf &&
      git config commit.gpgsign true
vscode:
  extensions:
    - aaron-bond.better-comments
    - ahmadawais.shades-of-purple
    - avraammavridis.vsc-react-documentation
    - bierner.color-info
    - bradlc.vscode-tailwindcss
    - bungcip.better-toml
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - CodeSandbox-io.codesandbox-projects-theme
    - cweijan.vscode-mysql-client2
    - DaltonMenezes.aura-theme
    - dbaeumer.vscode-eslint
    - DominicVonk.parameter-hints
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - GitHub.copilot
    - GitHub.github-vscode-theme
    - GitHub.vscode-pull-request-github
    - golang.go
    - Gruntfuggly.todo-tree
    - jsDelivr.jsdelivr
    - k--kato.intellij-idea-keybindings
    - manuth.eslint-language-service
    - markwylde.vscode-filesize
    - mechatroner.rainbow-csv
    - mikestead.dotenv
    - mongodb.mongodb-vscode
    - monokai.theme-monokai-pro-vscode
    - ms-python.python
    - ms-vscode.cpptools
    - ms-vsliveshare.vsliveshare-pack
    - naumovs.color-highlight
    - ngryman.codesandbox-theme
    - njzy.stats-bar
    - oderwat.indent-rainbow
    - pflannery.vscode-versionlens
    - PKief.material-icon-theme
    - Prisma.prisma-insider
    - rangav.vscode-thunder-client
    - redhat.java
    - redwan-hossain.auto-rename-tag-clone
    - sdras.night-owl
    - steoates.autoimport
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - vlanguage.vscode-vlang
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-initializr
    - wix.vscode-import-cost
    - zaaack.markdown-editor
